# Generated by Django 2.1.3 on 2018-11-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('last_edit_date', models.DateTimeField(verbose_name='date last edited')),
                ('post_text', models.TextField(max_length=25000)),
            ],
        ),
    ]
