# Generated by Django 2.1.3 on 2018-11-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_text',
            new_name='post_body',
        ),
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
