# Generated by Django 2.1.3 on 2018-11-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181107_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_summary',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
