# Generated by Django 2.1.3 on 2018-11-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181113_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('about_us', models.TextField(max_length=20000)),
                ('about_this_blog', models.TextField(max_length=20000)),
                ('contact_data', models.TextField(max_length=20000)),
            ],
        ),
    ]
