# Generated by Django 2.1.3 on 2018-11-16 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogsettings',
            old_name='about_this_blog',
            new_name='about',
        ),
        migrations.RemoveField(
            model_name='blogsettings',
            name='about_us',
        ),
    ]
