# Generated by Django 2.1.3 on 2018-11-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181116_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_edit_date',
            field=models.DateTimeField(null=True, verbose_name='date last edited'),
        ),
    ]
