# Generated by Django 2.1.3 on 2018-11-24 09:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=25000),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000),
        ),
    ]
