# Generated by Django 2.1.3 on 2018-11-26 06:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20181124_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsettings',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='contact_data',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
